### ISSUE TITLE
omv2mqtt: error in logs

### ISSUE THREAD

**Issue by DST73** [GollumDom/addon-repository#6]
Hi,
I am running OMV in a Proxmox VM. Looks like it does not support cputemp which ends in an exception.
That would be a big deal if it does not lead to that the whole service section is missing

OMV in a Proxmox VM

![image](https://github.com/user-attachments/assets/eb725913-cbc2-47c4-86cc-6742006466c4)

OMV on my Pi4

![image](https://github.com/user-attachments/assets/664b2784-18d7-4b56-9078-a4d3dd06d8f4)

````
OMV login success

Update MQTT data

ERROR: TypeError: Cannot read properties of null (reading 'cputemp')

    at updateSystem (/app/dist/index.js:429:49)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Promise.all (index 1)

    at async mainLoop (/app/dist/index.js:844:17)

OMV login success

Update MQTT data

ERROR: TypeError: Cannot read properties of null (reading 'cputemp')

    at updateSystem (/app/dist/index.js:429:49)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Promise.all (index 1)

    at async mainLoop (/app/dist/index.js:844:17)

OMV login success

Update MQTT data

ERROR: TypeError: Cannot read properties of null (reading 'cputemp')

    at updateSystem (/app/dist/index.js:429:49)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Promise.all (index 1)

    at async mainLoop (/app/dist/index.js:844:17)
````

Would be great if such an error does not end in the whole system information is missing

**Comment by Smeagolworms4** [comment]
https://github.com/Smeagolworms4/omv2mqtt/issues/1
